#!/bin/sh

files='util.py tok.py
fasttext.py cnn.py
fasttext_categories.py cnn_categories.py
fasttext_categories_v2.py cnn_categories_v2.py
fasttext_binary.py cnn_binary.py
fasttext_binary_categories.py cnn_binary_categories.py
evaluate.py evaluate_binary.py
run_binary run_binary_evaluation'

scp ${files} ieeta:/backup
